#pragma once

enum T3D_GAMEPAD_CODE
{
    T3D_GAMEPAD_CODE_PAD_A = 0,
    T3D_GAMEPAD_CODE_PAD_B = 1,
    T3D_GAMEPAD_CODE_PAD_X = 2,
    T3D_GAMEPAD_CODE_PAD_Y = 3,

    T3D_GAMEPAD_CODE_PAD_LEFT_BUMPER = 4,
    T3D_GAMEPAD_CODE_PAD_RIGHT_BUMPER = 5,

    T3D_GAMEPAD_CODE_PAD_BACK = 6,
    T3D_GAMEPAD_CODE_PAD_START = 7,
    T3D_GAMEPAD_CODE_PAD_GUIDE = 8,

    T3D_GAMEPAD_CODE_PAD_LEFT_THUMB = 9,
    T3D_GAMEPAD_CODE_PAD_RIGHT_THUMB = 10,

    T3D_GAMEPAD_CODE_PAD_UP = 11,
    T3D_GAMEPAD_CODE_PAD_RIGHT = 12,
    T3D_GAMEPAD_CODE_PAD_DOWN = 13,
    T3D_GAMEPAD_CODE_PAD_LEFT = 14,

    T3D_GAMEPAD_CODE_PAD_LAST = T3D_GAMEPAD_CODE_PAD_LEFT,

    T3D_GAMEPAD_CODE_PAD_CROSS = T3D_GAMEPAD_CODE_PAD_A,
    T3D_GAMEPAD_CODE_PAD_CIRCLE = T3D_GAMEPAD_CODE_PAD_B,
    T3D_GAMEPAD_CODE_PAD_SQUARE = T3D_GAMEPAD_CODE_PAD_X,
    T3D_GAMEPAD_CODE_PAD_TRIANGLE = T3D_GAMEPAD_CODE_PAD_Y
};

enum T3D_GAMEPAD_AXIS
{
    T3D_GAMEPAD_AXIS_LEFT_X = 0,
    T3D_GAMEPAD_AXIS_LEFT_Y = 1,
    T3D_GAMEPAD_AXIS_RIGHT_X = 2,
    T3D_GAMEPAD_AXIS_RIGHT_Y = 3,

    T3D_GAMEPAD_AXIS_LEFT_TRIGGER = 4,
    T3D_GAMEPAD_AXIS_RIGHT_TRIGGER = 5,

    T3D_GAMEPAD_AXIS_LAST = T3D_GAMEPAD_AXIS_RIGHT_TRIGGER
};
